#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CoreAuricCellsPresenterGroup

#include "Basic.hpp"

#include "DBDUIPresenters_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CoreAuricCellsPresenterGroup.BP_CoreAuricCellsPresenterGroup_C
// 0x0000 (0x0058 - 0x0058)
class UBP_CoreAuricCellsPresenterGroup_C final : public UPresenterGroup
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CoreAuricCellsPresenterGroup_C">();
	}
	static class UBP_CoreAuricCellsPresenterGroup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CoreAuricCellsPresenterGroup_C>();
	}
};
static_assert(alignof(UBP_CoreAuricCellsPresenterGroup_C) == 0x000008, "Wrong alignment on UBP_CoreAuricCellsPresenterGroup_C");
static_assert(sizeof(UBP_CoreAuricCellsPresenterGroup_C) == 0x000058, "Wrong size on UBP_CoreAuricCellsPresenterGroup_C");

}

