#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EscapeMap

#include "Basic.hpp"

#include "DBDInteraction_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EscapeMap.BP_EscapeMap_C
// 0x0000 (0x0780 - 0x0780)
class UBP_EscapeMap_C final : public UEscapeMapInteraction
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EscapeMap_C">();
	}
	static class UBP_EscapeMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EscapeMap_C>();
	}
};
static_assert(alignof(UBP_EscapeMap_C) == 0x000010, "Wrong alignment on UBP_EscapeMap_C");
static_assert(sizeof(UBP_EscapeMap_C) == 0x000780, "Wrong size on UBP_EscapeMap_C");

}

