#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FogOverride

#include "Basic.hpp"

#include "BP_FogOverride_classes.hpp"
#include "BP_FogOverride_parameters.hpp"


namespace SDK
{

// Function BP_FogOverride.BP_FogOverride_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_FogOverride_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FogOverride_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

