#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IndLightLong

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IndLightLong.BP_IndLightLong_C
// 0x0010 (0x02B0 - 0x02A0)
class ABP_IndLightLong_C final : public AActor
{
public:
	class USpotLightComponent*                    SpotLight;                                         // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_StoreHouse01_Light01;                           // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_IndLightLong_C">();
	}
	static class ABP_IndLightLong_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_IndLightLong_C>();
	}
};
static_assert(alignof(ABP_IndLightLong_C) == 0x000008, "Wrong alignment on ABP_IndLightLong_C");
static_assert(sizeof(ABP_IndLightLong_C) == 0x0002B0, "Wrong size on ABP_IndLightLong_C");
static_assert(offsetof(ABP_IndLightLong_C, SpotLight) == 0x0002A0, "Member 'ABP_IndLightLong_C::SpotLight' has a wrong offset!");
static_assert(offsetof(ABP_IndLightLong_C, SM_StoreHouse01_Light01) == 0x0002A8, "Member 'ABP_IndLightLong_C::SM_StoreHouse01_Light01' has a wrong offset!");

}

