#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_K23_ShowKnife_OnSurvivor_02

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_K23_ShowKnife_OnSurvivor_02.BP_K23_ShowKnife_OnSurvivor_02_C
// 0x0010 (0x02B0 - 0x02A0)
class ABP_K23_ShowKnife_OnSurvivor_02_C final : public AActor
{
public:
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_K23_ShowKnife_OnSurvivor_02_C">();
	}
	static class ABP_K23_ShowKnife_OnSurvivor_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_K23_ShowKnife_OnSurvivor_02_C>();
	}
};
static_assert(alignof(ABP_K23_ShowKnife_OnSurvivor_02_C) == 0x000008, "Wrong alignment on ABP_K23_ShowKnife_OnSurvivor_02_C");
static_assert(sizeof(ABP_K23_ShowKnife_OnSurvivor_02_C) == 0x0002B0, "Wrong size on ABP_K23_ShowKnife_OnSurvivor_02_C");
static_assert(offsetof(ABP_K23_ShowKnife_OnSurvivor_02_C, SkeletalMesh) == 0x0002A0, "Member 'ABP_K23_ShowKnife_OnSurvivor_02_C::SkeletalMesh' has a wrong offset!");
static_assert(offsetof(ABP_K23_ShowKnife_OnSurvivor_02_C, DefaultSceneRoot) == 0x0002A8, "Member 'ABP_K23_ShowKnife_OnSurvivor_02_C::DefaultSceneRoot' has a wrong offset!");

}

