#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Toolbox_002

#include "Basic.hpp"

#include "ToolBox_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Toolbox_002.BP_Toolbox_002_C
// 0x0000 (0x05C8 - 0x05C8)
class ABP_Toolbox_002_C final : public AToolBox_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Toolbox_002_C">();
	}
	static class ABP_Toolbox_002_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Toolbox_002_C>();
	}
};
static_assert(alignof(ABP_Toolbox_002_C) == 0x000008, "Wrong alignment on ABP_Toolbox_002_C");
static_assert(sizeof(ABP_Toolbox_002_C) == 0x0005C8, "Wrong size on ABP_Toolbox_002_C");

}

