#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_FrenzyFunctionLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPFL_FrenzyFunctionLibrary.BPFL_FrenzyFunctionLibrary_C
// 0x0000 (0x0030 - 0x0030)
class UBPFL_FrenzyFunctionLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static void IsInFrenzy(class ADBDPlayer* Player, class UObject* __WorldContext, bool* Param_IsInFrenzy);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPFL_FrenzyFunctionLibrary_C">();
	}
	static class UBPFL_FrenzyFunctionLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPFL_FrenzyFunctionLibrary_C>();
	}
};
static_assert(alignof(UBPFL_FrenzyFunctionLibrary_C) == 0x000008, "Wrong alignment on UBPFL_FrenzyFunctionLibrary_C");
static_assert(sizeof(UBPFL_FrenzyFunctionLibrary_C) == 0x000030, "Wrong size on UBPFL_FrenzyFunctionLibrary_C");

}

