#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_K31

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_K31.BPI_K31_C
// 0x0000 (0x0030 - 0x0030)
class IBPI_K31_C final : public IInterface
{
public:
	void K31_AddScanningLines();
	void K31_Mori_DissolveDroneIn();
	void K31_RemoveClawTrap();
	void K31_RemoveScanningLines();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_K31_C">();
	}
	static class IBPI_K31_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_K31_C>();
	}
};
static_assert(alignof(IBPI_K31_C) == 0x000008, "Wrong alignment on IBPI_K31_C");
static_assert(sizeof(IBPI_K31_C) == 0x000030, "Wrong size on IBPI_K31_C");

}

