#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Effect_Nightmare_Survivor

#include "Basic.hpp"

#include "BPI_Effect_Nightmare_Survivor_classes.hpp"
#include "BPI_Effect_Nightmare_Survivor_parameters.hpp"


namespace SDK
{

// Function BPI_Effect_Nightmare_Survivor.BPI_Effect_Nightmare_Survivor_C.HandleDreamStateChangedVFX
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsInDreamworld                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    LocallyObservedChanged                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_Effect_Nightmare_Survivor_C::HandleDreamStateChangedVFX(bool IsInDreamworld, bool LocallyObservedChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPI_Effect_Nightmare_Survivor_C", "HandleDreamStateChangedVFX");

	Params::BPI_Effect_Nightmare_Survivor_C_HandleDreamStateChangedVFX Parms{};

	Parms.IsInDreamworld = IsInDreamworld;
	Parms.LocallyObservedChanged = LocallyObservedChanged;

	UObject::ProcessEvent(Func, &Parms);
}

}

