#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClosetBlindnessEffect

#include "Basic.hpp"

#include "ClosetBlindnessEffect_classes.hpp"
#include "ClosetBlindnessEffect_parameters.hpp"


namespace SDK
{

// Function ClosetBlindnessEffect.ClosetBlindnessEffect_C.OnInitialized
// (Event, Public, BlueprintEvent)

void UClosetBlindnessEffect_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClosetBlindnessEffect_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ClosetBlindnessEffect.ClosetBlindnessEffect_C.OnGameEventDispatched
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     GameEventType                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameEventData                   GameEventData                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UClosetBlindnessEffect_C::OnGameEventDispatched(const struct FGameplayTag& GameEventType, const struct FGameEventData& GameEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClosetBlindnessEffect_C", "OnGameEventDispatched");

	Params::ClosetBlindnessEffect_C_OnGameEventDispatched Parms{};

	Parms.GameEventType = std::move(GameEventType);
	Parms.GameEventData = std::move(GameEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ClosetBlindnessEffect.ClosetBlindnessEffect_C.OnAnyPlayerExitCloset
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UClosetBlindnessEffect_C::OnAnyPlayerExitCloset(class UObject* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClosetBlindnessEffect_C", "OnAnyPlayerExitCloset");

	Params::ClosetBlindnessEffect_C_OnAnyPlayerExitCloset Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ClosetBlindnessEffect.ClosetBlindnessEffect_C.ExecuteUbergraph_ClosetBlindnessEffect
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UClosetBlindnessEffect_C::ExecuteUbergraph_ClosetBlindnessEffect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ClosetBlindnessEffect_C", "ExecuteUbergraph_ClosetBlindnessEffect");

	Params::ClosetBlindnessEffect_C_ExecuteUbergraph_ClosetBlindnessEffect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

