#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataTableUtilities

#include "Basic.hpp"

#include "DataTableUtilities_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class DataTableUtilities.DBDTunableOverrides
// 0x0010 (0x0048 - 0x0038)
class UDBDTunableOverrides final : public UDataAsset
{
public:
	TArray<struct FDBDTunableRowHandleOverride>   _overrides;                                        // 0x0038(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DBDTunableOverrides">();
	}
	static class UDBDTunableOverrides* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDBDTunableOverrides>();
	}
};
static_assert(alignof(UDBDTunableOverrides) == 0x000008, "Wrong alignment on UDBDTunableOverrides");
static_assert(sizeof(UDBDTunableOverrides) == 0x000048, "Wrong size on UDBDTunableOverrides");
static_assert(offsetof(UDBDTunableOverrides, _overrides) == 0x000038, "Member 'UDBDTunableOverrides::_overrides' has a wrong offset!");

}

