#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DropManual

#include "Basic.hpp"

#include "DeadByDaylight_structs.hpp"
#include "DBDSharedTypes_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function DropManual.DropManual_C.AuthorityApplyDropPenalty
// 0x0040 (0x0040 - 0x0000)
struct DropManual_C_AuthorityApplyDropPenalty final
{
public:
	class ASlasherPlayer*                         CallFunc_GetSlasher_ReturnValue;                   // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetTunableValue_ReturnValue;              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ACamperPlayer*                          CallFunc_GetCamper_ReturnValue;                    // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCamperHealthComponent*                 CallFunc_GetHealthComponent_ReturnValue;           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECamperDamageState                            CallFunc_GetDamageState_ReturnValue;               // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B[0x5];                                       // 0x002B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UChargeableComponent*                   CallFunc_GetWiggleChargeable_ReturnValue;          // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DropManual_C_AuthorityApplyDropPenalty) == 0x000008, "Wrong alignment on DropManual_C_AuthorityApplyDropPenalty");
static_assert(sizeof(DropManual_C_AuthorityApplyDropPenalty) == 0x000040, "Wrong size on DropManual_C_AuthorityApplyDropPenalty");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_GetSlasher_ReturnValue) == 0x000000, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_GetSlasher_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_GetTunableValue_ReturnValue) == 0x000008, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_GetTunableValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_GetCamper_ReturnValue) == 0x000010, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_GetCamper_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_GetHealthComponent_ReturnValue) == 0x000020, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_GetHealthComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_IsValid_ReturnValue_1) == 0x000028, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_GetDamageState_ReturnValue) == 0x000029, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_GetDamageState_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00002A, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_GetWiggleChargeable_ReturnValue) == 0x000030, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_GetWiggleChargeable_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_IsValid_ReturnValue_2) == 0x000038, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DropManual_C_AuthorityApplyDropPenalty, CallFunc_HasAuthority_ReturnValue) == 0x000039, "Member 'DropManual_C_AuthorityApplyDropPenalty::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");

// Function DropManual.DropManual_C.ExecuteUbergraph_DropManual
// 0x0040 (0x0040 - 0x0000)
struct DropManual_C_ExecuteUbergraph_DropManual final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ADBDPlayer*                             K2Node_CustomEvent_picker;                         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ADBDPlayer*                             K2Node_Event_player;                               // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetTunableValue_ReturnValue;              // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0020(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0038(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DropManual_C_ExecuteUbergraph_DropManual) == 0x000008, "Wrong alignment on DropManual_C_ExecuteUbergraph_DropManual");
static_assert(sizeof(DropManual_C_ExecuteUbergraph_DropManual) == 0x000040, "Wrong size on DropManual_C_ExecuteUbergraph_DropManual");
static_assert(offsetof(DropManual_C_ExecuteUbergraph_DropManual, EntryPoint) == 0x000000, "Member 'DropManual_C_ExecuteUbergraph_DropManual::EntryPoint' has a wrong offset!");
static_assert(offsetof(DropManual_C_ExecuteUbergraph_DropManual, K2Node_CustomEvent_picker) == 0x000008, "Member 'DropManual_C_ExecuteUbergraph_DropManual::K2Node_CustomEvent_picker' has a wrong offset!");
static_assert(offsetof(DropManual_C_ExecuteUbergraph_DropManual, K2Node_Event_player) == 0x000010, "Member 'DropManual_C_ExecuteUbergraph_DropManual::K2Node_Event_player' has a wrong offset!");
static_assert(offsetof(DropManual_C_ExecuteUbergraph_DropManual, CallFunc_GetTunableValue_ReturnValue) == 0x000018, "Member 'DropManual_C_ExecuteUbergraph_DropManual::CallFunc_GetTunableValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_ExecuteUbergraph_DropManual, CallFunc_Greater_FloatFloat_ReturnValue) == 0x00001C, "Member 'DropManual_C_ExecuteUbergraph_DropManual::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_ExecuteUbergraph_DropManual, K2Node_CreateDelegate_OutputDelegate) == 0x000020, "Member 'DropManual_C_ExecuteUbergraph_DropManual::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(DropManual_C_ExecuteUbergraph_DropManual, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000038, "Member 'DropManual_C_ExecuteUbergraph_DropManual::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");

// Function DropManual.DropManual_C.Initialize
// 0x0020 (0x0020 - 0x0000)
struct DropManual_C_Initialize final
{
public:
	class ACamperPlayer*                          Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class ADBDPlayer* Picker)>     K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0014)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DropManual_C_Initialize) == 0x000008, "Wrong alignment on DropManual_C_Initialize");
static_assert(sizeof(DropManual_C_Initialize) == 0x000020, "Wrong size on DropManual_C_Initialize");
static_assert(offsetof(DropManual_C_Initialize, Player) == 0x000000, "Member 'DropManual_C_Initialize::Player' has a wrong offset!");
static_assert(offsetof(DropManual_C_Initialize, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'DropManual_C_Initialize::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");

// Function DropManual.DropManual_C.OnInteractionExitStart
// 0x0008 (0x0008 - 0x0000)
struct DropManual_C_OnInteractionExitStart final
{
public:
	class ADBDPlayer*                             Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DropManual_C_OnInteractionExitStart) == 0x000008, "Wrong alignment on DropManual_C_OnInteractionExitStart");
static_assert(sizeof(DropManual_C_OnInteractionExitStart) == 0x000008, "Wrong size on DropManual_C_OnInteractionExitStart");
static_assert(offsetof(DropManual_C_OnInteractionExitStart, Player) == 0x000000, "Member 'DropManual_C_OnInteractionExitStart::Player' has a wrong offset!");

// Function DropManual.DropManual_C.OnPickedUpEnd_Event
// 0x0008 (0x0008 - 0x0000)
struct DropManual_C_OnPickedUpEnd_Event final
{
public:
	class ADBDPlayer*                             Picker;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DropManual_C_OnPickedUpEnd_Event) == 0x000008, "Wrong alignment on DropManual_C_OnPickedUpEnd_Event");
static_assert(sizeof(DropManual_C_OnPickedUpEnd_Event) == 0x000008, "Wrong size on DropManual_C_OnPickedUpEnd_Event");
static_assert(offsetof(DropManual_C_OnPickedUpEnd_Event, Picker) == 0x000000, "Member 'DropManual_C_OnPickedUpEnd_Event::Picker' has a wrong offset!");

// Function DropManual.DropManual_C.IsBeingCaughtInTrap
// 0x0020 (0x0020 - 0x0000)
struct DropManual_C_IsBeingCaughtInTrap final
{
public:
	class ADBDPlayer*                             Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCaught;                                          // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UInteractionDefinition*                 CallFunc_GetCurrentInteraction_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DropManual_C_IsBeingCaughtInTrap) == 0x000008, "Wrong alignment on DropManual_C_IsBeingCaughtInTrap");
static_assert(sizeof(DropManual_C_IsBeingCaughtInTrap) == 0x000020, "Wrong size on DropManual_C_IsBeingCaughtInTrap");
static_assert(offsetof(DropManual_C_IsBeingCaughtInTrap, Player) == 0x000000, "Member 'DropManual_C_IsBeingCaughtInTrap::Player' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsBeingCaughtInTrap, IsCaught) == 0x000008, "Member 'DropManual_C_IsBeingCaughtInTrap::IsCaught' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsBeingCaughtInTrap, CallFunc_GetCurrentInteraction_ReturnValue) == 0x000010, "Member 'DropManual_C_IsBeingCaughtInTrap::CallFunc_GetCurrentInteraction_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsBeingCaughtInTrap, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'DropManual_C_IsBeingCaughtInTrap::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsBeingCaughtInTrap, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x000019, "Member 'DropManual_C_IsBeingCaughtInTrap::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");

// Function DropManual.DropManual_C.IsInteractionPossibleBP
// 0x0040 (0x0040 - 0x0000)
struct DropManual_C_IsInteractionPossibleBP final
{
public:
	const class ADBDPlayer*                       Player;                                            // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EInputInteractionType                         InteractionType;                                   // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0009(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInteractionPossibleBP_ReturnValue;      // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ASlasherPlayer*                         K2Node_DynamicCast_AsSlasher_Player;               // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBeingCaughtInTrap_IsCaught;             // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasSlasherClearPathToDropOffPoint_ReturnValue; // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ACamperPlayer*                          CallFunc_GetCamper_ReturnValue;                    // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPerkManager*                           CallFunc_GetPerkManager_ReturnValue;               // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasPerkFlag_ReturnValue;                  // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x003B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x003E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_4;                 // 0x003F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DropManual_C_IsInteractionPossibleBP) == 0x000008, "Wrong alignment on DropManual_C_IsInteractionPossibleBP");
static_assert(sizeof(DropManual_C_IsInteractionPossibleBP) == 0x000040, "Wrong size on DropManual_C_IsInteractionPossibleBP");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, Player) == 0x000000, "Member 'DropManual_C_IsInteractionPossibleBP::Player' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, InteractionType) == 0x000008, "Member 'DropManual_C_IsInteractionPossibleBP::InteractionType' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, ReturnValue) == 0x000009, "Member 'DropManual_C_IsInteractionPossibleBP::ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_IsInteractionPossibleBP_ReturnValue) == 0x00000A, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_IsInteractionPossibleBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x00000B, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, K2Node_DynamicCast_AsSlasher_Player) == 0x000010, "Member 'DropManual_C_IsInteractionPossibleBP::K2Node_DynamicCast_AsSlasher_Player' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'DropManual_C_IsInteractionPossibleBP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_IsBeingCaughtInTrap_IsCaught) == 0x000019, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_IsBeingCaughtInTrap_IsCaught' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_HasSlasherClearPathToDropOffPoint_ReturnValue) == 0x00001A, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_HasSlasherClearPathToDropOffPoint_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_Not_PreBool_ReturnValue) == 0x00001B, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_GetCamper_ReturnValue) == 0x000020, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_GetCamper_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_BooleanAND_ReturnValue) == 0x000028, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_GetPerkManager_ReturnValue) == 0x000030, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_GetPerkManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_IsValid_ReturnValue) == 0x000038, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_HasPerkFlag_ReturnValue) == 0x000039, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_HasPerkFlag_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_IsValid_ReturnValue_1) == 0x00003A, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_Not_PreBool_ReturnValue_1) == 0x00003B, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_BooleanAND_ReturnValue_1) == 0x00003C, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_BooleanAND_ReturnValue_2) == 0x00003D, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_BooleanAND_ReturnValue_3) == 0x00003E, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleBP, CallFunc_BooleanAND_ReturnValue_4) == 0x00003F, "Member 'DropManual_C_IsInteractionPossibleBP::CallFunc_BooleanAND_ReturnValue_4' has a wrong offset!");

// Function DropManual.DropManual_C.IsInteractionPossibleClient
// 0x0048 (0x0048 - 0x0000)
struct DropManual_C_IsInteractionPossibleClient final
{
public:
	const class ADBDPlayer*                       Player;                                            // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EInputInteractionType                         InteractionType;                                   // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0009(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetTunableValue_ReturnValue;              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ACamperPlayer*                          CallFunc_GetCamper_ReturnValue;                    // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UChargeableComponent*                   CallFunc_GetWiggleChargeable_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetPercentComplete_ReturnValue;           // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPerkManager*                           CallFunc_GetPerkManager_ReturnValue;               // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasPerkFlag_ReturnValue;                  // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0043(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DropManual_C_IsInteractionPossibleClient) == 0x000008, "Wrong alignment on DropManual_C_IsInteractionPossibleClient");
static_assert(sizeof(DropManual_C_IsInteractionPossibleClient) == 0x000048, "Wrong size on DropManual_C_IsInteractionPossibleClient");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, Player) == 0x000000, "Member 'DropManual_C_IsInteractionPossibleClient::Player' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, InteractionType) == 0x000008, "Member 'DropManual_C_IsInteractionPossibleClient::InteractionType' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, ReturnValue) == 0x000009, "Member 'DropManual_C_IsInteractionPossibleClient::ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_GetTunableValue_ReturnValue) == 0x00000C, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_GetTunableValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000010, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_GetCamper_ReturnValue) == 0x000018, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_GetCamper_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_GetWiggleChargeable_ReturnValue) == 0x000020, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_GetWiggleChargeable_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_GetPercentComplete_ReturnValue) == 0x00002C, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_GetPercentComplete_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_Less_FloatFloat_ReturnValue) == 0x000030, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_IsValid_ReturnValue_1) == 0x000031, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_GetPerkManager_ReturnValue) == 0x000038, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_GetPerkManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_BooleanAND_ReturnValue) == 0x000040, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_HasPerkFlag_ReturnValue) == 0x000041, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_HasPerkFlag_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_IsValid_ReturnValue_2) == 0x000042, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_Not_PreBool_ReturnValue) == 0x000043, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_BooleanAND_ReturnValue_1) == 0x000044, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DropManual_C_IsInteractionPossibleClient, CallFunc_BooleanAND_ReturnValue_2) == 0x000045, "Member 'DropManual_C_IsInteractionPossibleClient::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");

}

