#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FinishGameWithCharacterPerksAchievementBP

#include "Basic.hpp"

#include "Achievements_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FinishGameWithCharacterPerksAchievementBP.FinishGameWithCharacterPerksAchievementBP_C
// 0x0000 (0x0078 - 0x0078)
class UFinishGameWithCharacterPerksAchievementBP_C final : public UFinishGameWithCharacterPerksAchievement
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FinishGameWithCharacterPerksAchievementBP_C">();
	}
	static class UFinishGameWithCharacterPerksAchievementBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFinishGameWithCharacterPerksAchievementBP_C>();
	}
};
static_assert(alignof(UFinishGameWithCharacterPerksAchievementBP_C) == 0x000008, "Wrong alignment on UFinishGameWithCharacterPerksAchievementBP_C");
static_assert(sizeof(UFinishGameWithCharacterPerksAchievementBP_C) == 0x000078, "Wrong size on UFinishGameWithCharacterPerksAchievementBP_C");

}

