#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InterruptAtInterrupteeLocation

#include "Basic.hpp"

#include "DeadByDaylight_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass InterruptAtInterrupteeLocation.InterruptAtInterrupteeLocation_C
// 0x0010 (0x03C0 - 0x03B0)
class UInterruptAtInterrupteeLocation_C : public UInterruptionDefinition
{
public:
	double                                        Snap_Distance;                                     // 0x03B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FRotator GetInterruptionSnapPointRotationForInterruptor(const class ADBDPlayer* Interruptor, const class ADBDPlayer* Interruptee) const;
	struct FVector GetInterruptionSnapPointPositionForInterruptor(const class ADBDPlayer* Interruptor, const class ADBDPlayer* Interruptee) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"InterruptAtInterrupteeLocation_C">();
	}
	static class UInterruptAtInterrupteeLocation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInterruptAtInterrupteeLocation_C>();
	}
};
static_assert(alignof(UInterruptAtInterrupteeLocation_C) == 0x000010, "Wrong alignment on UInterruptAtInterrupteeLocation_C");
static_assert(sizeof(UInterruptAtInterrupteeLocation_C) == 0x0003C0, "Wrong size on UInterruptAtInterrupteeLocation_C");
static_assert(offsetof(UInterruptAtInterrupteeLocation_C, Snap_Distance) == 0x0003B0, "Member 'UInterruptAtInterrupteeLocation_C::Snap_Distance' has a wrong offset!");

}

