#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: K32KillerPodRestrictedZoneBox

#include "Basic.hpp"

#include "K32KillerPodRestrictedZoneBox_classes.hpp"
#include "K32KillerPodRestrictedZoneBox_parameters.hpp"


namespace SDK
{

// Function K32KillerPodRestrictedZoneBox.K32KillerPodRestrictedZoneBox_C.GetStaticMesh
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UStaticMeshComponent*             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UStaticMeshComponent* AK32KillerPodRestrictedZoneBox_C::GetStaticMesh() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("K32KillerPodRestrictedZoneBox_C", "GetStaticMesh");

	Params::K32KillerPodRestrictedZoneBox_C_GetStaticMesh Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

