#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MaxBloodpointsAllCategoriesAchievementBP

#include "Basic.hpp"

#include "Achievements_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MaxBloodpointsAllCategoriesAchievementBP.MaxBloodpointsAllCategoriesAchievementBP_C
// 0x0000 (0x0078 - 0x0078)
class UMaxBloodpointsAllCategoriesAchievementBP_C final : public UMaxBloodpointsAllCategoriesAchievement
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MaxBloodpointsAllCategoriesAchievementBP_C">();
	}
	static class UMaxBloodpointsAllCategoriesAchievementBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMaxBloodpointsAllCategoriesAchievementBP_C>();
	}
};
static_assert(alignof(UMaxBloodpointsAllCategoriesAchievementBP_C) == 0x000008, "Wrong alignment on UMaxBloodpointsAllCategoriesAchievementBP_C");
static_assert(sizeof(UMaxBloodpointsAllCategoriesAchievementBP_C) == 0x000078, "Wrong size on UMaxBloodpointsAllCategoriesAchievementBP_C");

}

