#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OpenChest

#include "Basic.hpp"

#include "DBDInteraction_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OpenChest.OpenChest_C
// 0x0000 (0x0900 - 0x0900)
class UOpenChest_C final : public UOpenChestInteraction
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"OpenChest_C">();
	}
	static class UOpenChest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOpenChest_C>();
	}
};
static_assert(alignof(UOpenChest_C) == 0x000010, "Wrong alignment on UOpenChest_C");
static_assert(sizeof(UOpenChest_C) == 0x000900, "Wrong size on UOpenChest_C");

}

