#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PulldownWhileCarriedByKiller

#include "Basic.hpp"

#include "PulldownWhileCarriedByKiller_classes.hpp"
#include "PulldownWhileCarriedByKiller_parameters.hpp"


namespace SDK
{

// Function PulldownWhileCarriedByKiller.PulldownWhileCarriedByKiller_C.OnInteractionUpdateStart
// (Event, Protected, BlueprintEvent)
// Parameters:
// class ADBDPlayer*                       Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPulldownWhileCarriedByKiller_C::OnInteractionUpdateStart(class ADBDPlayer* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PulldownWhileCarriedByKiller_C", "OnInteractionUpdateStart");

	Params::PulldownWhileCarriedByKiller_C_OnInteractionUpdateStart Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PulldownWhileCarriedByKiller.PulldownWhileCarriedByKiller_C.ExecuteUbergraph_PulldownWhileCarriedByKiller
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPulldownWhileCarriedByKiller_C::ExecuteUbergraph_PulldownWhileCarriedByKiller(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PulldownWhileCarriedByKiller_C", "ExecuteUbergraph_PulldownWhileCarriedByKiller");

	Params::PulldownWhileCarriedByKiller_C_ExecuteUbergraph_PulldownWhileCarriedByKiller Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PulldownWhileCarriedByKiller.PulldownWhileCarriedByKiller_C.IsPulldownInteractionPossible
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class ADBDPlayer*                       Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UPulldownWhileCarriedByKiller_C::IsPulldownInteractionPossible(class ADBDPlayer* Player) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PulldownWhileCarriedByKiller_C", "IsPulldownInteractionPossible");

	Params::PulldownWhileCarriedByKiller_C_IsPulldownInteractionPossible Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PulldownWhileCarriedByKiller.PulldownWhileCarriedByKiller_C.IsOwningCamperCarriedByKiller
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class ADBDPlayer*                       Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    IsCamperCarriedByKiller                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPulldownWhileCarriedByKiller_C::IsOwningCamperCarriedByKiller(class ADBDPlayer* Player, bool* IsCamperCarriedByKiller) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PulldownWhileCarriedByKiller_C", "IsOwningCamperCarriedByKiller");

	Params::PulldownWhileCarriedByKiller_C_IsOwningCamperCarriedByKiller Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);

	if (IsCamperCarriedByKiller != nullptr)
		*IsCamperCarriedByKiller = Parms.IsCamperCarriedByKiller;
}


// Function PulldownWhileCarriedByKiller.PulldownWhileCarriedByKiller_C.IsInteractionPossibleClient
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class ADBDPlayer*                       Player                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EInputInteractionType                   InteractionType                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UPulldownWhileCarriedByKiller_C::IsInteractionPossibleClient(const class ADBDPlayer* Player, EInputInteractionType InteractionType) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PulldownWhileCarriedByKiller_C", "IsInteractionPossibleClient");

	Params::PulldownWhileCarriedByKiller_C_IsInteractionPossibleClient Parms{};

	Parms.Player = Player;
	Parms.InteractionType = InteractionType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PulldownWhileCarriedByKiller.PulldownWhileCarriedByKiller_C.IsInteractionPossibleBP
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class ADBDPlayer*                       Player                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EInputInteractionType                   InteractionType                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UPulldownWhileCarriedByKiller_C::IsInteractionPossibleBP(const class ADBDPlayer* Player, EInputInteractionType InteractionType) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PulldownWhileCarriedByKiller_C", "IsInteractionPossibleBP");

	Params::PulldownWhileCarriedByKiller_C_IsInteractionPossibleBP Parms{};

	Parms.Player = Player;
	Parms.InteractionType = InteractionType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PulldownWhileCarriedByKiller.PulldownWhileCarriedByKiller_C.GetOwiningCamper
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class ADBDPlayer*                       Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ACamperPlayer*                    AsCamperPlayer                                         (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPulldownWhileCarriedByKiller_C::GetOwiningCamper(class ADBDPlayer* Player, class ACamperPlayer** AsCamperPlayer) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PulldownWhileCarriedByKiller_C", "GetOwiningCamper");

	Params::PulldownWhileCarriedByKiller_C_GetOwiningCamper Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);

	if (AsCamperPlayer != nullptr)
		*AsCamperPlayer = Parms.AsCamperPlayer;
}


// Function PulldownWhileCarriedByKiller.PulldownWhileCarriedByKiller_C.CanOverrideInteraction
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UInteractionDefinition*           Interaction                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UPulldownWhileCarriedByKiller_C::CanOverrideInteraction(const class UInteractionDefinition* Interaction) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PulldownWhileCarriedByKiller_C", "CanOverrideInteraction");

	Params::PulldownWhileCarriedByKiller_C_CanOverrideInteraction Parms{};

	Parms.Interaction = Interaction;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

