#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PurchasableItems

#include "Basic.hpp"

#include "DataTableUtilities_structs.hpp"


namespace SDK
{

// ScriptStruct PurchasableItems.PurchasableOperationData
// 0x0010 (0x0018 - 0x0008)
struct FPurchasableOperationData final : public FDBDTableRowBase
{
public:
	class FName                                   ID;                                                // 0x0008(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FPurchasableOperationData) == 0x000008, "Wrong alignment on FPurchasableOperationData");
static_assert(sizeof(FPurchasableOperationData) == 0x000018, "Wrong size on FPurchasableOperationData");
static_assert(offsetof(FPurchasableOperationData, ID) == 0x000008, "Member 'FPurchasableOperationData::ID' has a wrong offset!");

}

