#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScalableIconsDecorator

#include "Basic.hpp"

#include "DBDUIViewsCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ScalableIconsDecorator.ScalableIconsDecorator_C
// 0x0000 (0x0050 - 0x0050)
class UScalableIconsDecorator_C final : public URichTextBlockScalableImageDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ScalableIconsDecorator_C">();
	}
	static class UScalableIconsDecorator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScalableIconsDecorator_C>();
	}
};
static_assert(alignof(UScalableIconsDecorator_C) == 0x000008, "Wrong alignment on UScalableIconsDecorator_C");
static_assert(sizeof(UScalableIconsDecorator_C) == 0x000050, "Wrong size on UScalableIconsDecorator_C");

}

