#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextureUtilitiesCommon

#include "Basic.hpp"


namespace SDK
{

// Enum TextureUtilitiesCommon.ETextureImportFloatingPointFormat
// NumValues: 0x0005
enum class ETextureImportFloatingPointFormat : uint8
{
	HDR_F16                                  = 0,
	HDRCompressed_BC6                        = 1,
	HDR_F32_or_F16                           = 2,
	PreviousDefault                          = 0,
	ETextureImportFloatingPointFormat_MAX    = 3,
};

}

