#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VaultDefinition

#include "Basic.hpp"

#include "DeadByDaylight_classes.hpp"
#include "DBDSharedTypes_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass VaultDefinition.VaultDefinition_C
// 0x0000 (0x07E0 - 0x07E0)
class UVaultDefinition_C : public UVaultDefinition
{
public:
	bool IsInteractionPossibleClient(const class ADBDPlayer* Player, EInputInteractionType InteractionType) const;
	bool IsInteractionPossibleBP(const class ADBDPlayer* Player, EInputInteractionType InteractionType) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VaultDefinition_C">();
	}
	static class UVaultDefinition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVaultDefinition_C>();
	}
};
static_assert(alignof(UVaultDefinition_C) == 0x000010, "Wrong alignment on UVaultDefinition_C");
static_assert(sizeof(UVaultDefinition_C) == 0x0007E0, "Wrong size on UVaultDefinition_C");

}

