#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreSelectionArrowInputSwitcher

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DBDUIViewsCore_classes.hpp"
#include "Slate_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreSelectionArrowInputSwitcher.WBP_CoreSelectionArrowInputSwitcher_C
// 0x0010 (0x0410 - 0x0400)
class UWBP_CoreSelectionArrowInputSwitcher_C final : public UCoreInputSwitcherWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0400(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        Nudge;                                             // 0x0408(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void OnAlignmentChanged(ETextJustify NewAlignment);
	void ExecuteUbergraph_WBP_CoreSelectionArrowInputSwitcher(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreSelectionArrowInputSwitcher_C">();
	}
	static class UWBP_CoreSelectionArrowInputSwitcher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreSelectionArrowInputSwitcher_C>();
	}
};
static_assert(alignof(UWBP_CoreSelectionArrowInputSwitcher_C) == 0x000008, "Wrong alignment on UWBP_CoreSelectionArrowInputSwitcher_C");
static_assert(sizeof(UWBP_CoreSelectionArrowInputSwitcher_C) == 0x000410, "Wrong size on UWBP_CoreSelectionArrowInputSwitcher_C");
static_assert(offsetof(UWBP_CoreSelectionArrowInputSwitcher_C, UberGraphFrame) == 0x000400, "Member 'UWBP_CoreSelectionArrowInputSwitcher_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_CoreSelectionArrowInputSwitcher_C, Nudge) == 0x000408, "Member 'UWBP_CoreSelectionArrowInputSwitcher_C::Nudge' has a wrong offset!");

}

