#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreTutorialObjectivesContainer

#include "Basic.hpp"

#include "DBDUIViewsCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreTutorialObjectivesContainer.WBP_CoreTutorialObjectivesContainer_C
// 0x0000 (0x03B8 - 0x03B8)
class UWBP_CoreTutorialObjectivesContainer_C final : public UCoreTutorialObjectivesContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreTutorialObjectivesContainer_C">();
	}
	static class UWBP_CoreTutorialObjectivesContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreTutorialObjectivesContainer_C>();
	}
};
static_assert(alignof(UWBP_CoreTutorialObjectivesContainer_C) == 0x000008, "Wrong alignment on UWBP_CoreTutorialObjectivesContainer_C");
static_assert(sizeof(UWBP_CoreTutorialObjectivesContainer_C) == 0x0003B8, "Wrong size on UWBP_CoreTutorialObjectivesContainer_C");

}

