#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreArchiveTomeChallenges_VFXWidget

#include "Basic.hpp"

#include "FXWidget_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreArchiveTomeChallenges_VFXWidget.WBP_CoreArchiveTomeChallenges_VFXWidget_C
// 0x0000 (0x0308 - 0x0308)
class UWBP_CoreArchiveTomeChallenges_VFXWidget_C final : public UFXUserWidgetBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreArchiveTomeChallenges_VFXWidget_C">();
	}
	static class UWBP_CoreArchiveTomeChallenges_VFXWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreArchiveTomeChallenges_VFXWidget_C>();
	}
};
static_assert(alignof(UWBP_CoreArchiveTomeChallenges_VFXWidget_C) == 0x000008, "Wrong alignment on UWBP_CoreArchiveTomeChallenges_VFXWidget_C");
static_assert(sizeof(UWBP_CoreArchiveTomeChallenges_VFXWidget_C) == 0x000308, "Wrong size on UWBP_CoreArchiveTomeChallenges_VFXWidget_C");

}

