#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreMenuItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DBDUIViewsCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreMenuItem.WBP_CoreMenuItem_C
// 0x0008 (0x0550 - 0x0548)
class UWBP_CoreMenuItem_C final : public UCoreMenuItemWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0548(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_CoreMenuItem(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreMenuItem_C">();
	}
	static class UWBP_CoreMenuItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreMenuItem_C>();
	}
};
static_assert(alignof(UWBP_CoreMenuItem_C) == 0x000008, "Wrong alignment on UWBP_CoreMenuItem_C");
static_assert(sizeof(UWBP_CoreMenuItem_C) == 0x000550, "Wrong size on UWBP_CoreMenuItem_C");
static_assert(offsetof(UWBP_CoreMenuItem_C, UberGraphFrame) == 0x000548, "Member 'UWBP_CoreMenuItem_C::UberGraphFrame' has a wrong offset!");

}

