#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreStatusEffects_Item

#include "Basic.hpp"

#include "WBP_CoreStatusEffects_Item_classes.hpp"
#include "WBP_CoreStatusEffects_Item_parameters.hpp"


namespace SDK
{

// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.UpdateWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_CoreStatusEffects_Item_C::UpdateWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "UpdateWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.UpdatePercentageFill
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Percentage                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreStatusEffects_Item_C::UpdatePercentageFill(float Percentage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "UpdatePercentageFill");

	Params::WBP_CoreStatusEffects_Item_C_UpdatePercentageFill Parms{};

	Parms.Percentage = Percentage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.SetWidget
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_CoreStatusEffects_Item_C::SetWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "SetWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.SetGaugeFill
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           GaugeImage                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// double                                  Percentf                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreStatusEffects_Item_C::SetGaugeFill(class UImage* GaugeImage, double Percentf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "SetGaugeFill");

	Params::WBP_CoreStatusEffects_Item_C_SetGaugeFill Parms{};

	Parms.GaugeImage = GaugeImage;
	Parms.Percentf = Percentf;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.ResetWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_CoreStatusEffects_Item_C::ResetWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "ResetWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreStatusEffects_Item_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "PreConstruct");

	Params::WBP_CoreStatusEffects_Item_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreStatusEffects_Item_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "OnListItemObjectSet");

	Params::WBP_CoreStatusEffects_Item_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.ExecuteUbergraph_WBP_CoreStatusEffects_Item
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreStatusEffects_Item_C::ExecuteUbergraph_WBP_CoreStatusEffects_Item(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "ExecuteUbergraph_WBP_CoreStatusEffects_Item");

	Params::WBP_CoreStatusEffects_Item_C_ExecuteUbergraph_WBP_CoreStatusEffects_Item Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreStatusEffects_Item_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "BP_OnItemSelectionChanged");

	Params::WBP_CoreStatusEffects_Item_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CoreStatusEffects_Item_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "BP_OnItemExpansionChanged");

	Params::WBP_CoreStatusEffects_Item_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CoreStatusEffects_Item.WBP_CoreStatusEffects_Item_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_CoreStatusEffects_Item_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CoreStatusEffects_Item_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}

}

