#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CoreWallet

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DBDUIViewsCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CoreWallet.WBP_CoreWallet_C
// 0x0008 (0x0398 - 0x0390)
class UWBP_CoreWallet_C final : public UCoreWalletWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_WBP_CoreWallet(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CoreWallet_C">();
	}
	static class UWBP_CoreWallet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CoreWallet_C>();
	}
};
static_assert(alignof(UWBP_CoreWallet_C) == 0x000008, "Wrong alignment on UWBP_CoreWallet_C");
static_assert(sizeof(UWBP_CoreWallet_C) == 0x000398, "Wrong size on UWBP_CoreWallet_C");
static_assert(offsetof(UWBP_CoreWallet_C, UberGraphFrame) == 0x000390, "Member 'UWBP_CoreWallet_C::UberGraphFrame' has a wrong offset!");

}

