#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_K27

#include "Basic.hpp"

#include "WBP_K27_classes.hpp"
#include "WBP_K27_parameters.hpp"


namespace SDK
{

// Function WBP_K27.WBP_K27_C.UpdateStatic
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHoldingTape                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_K27_C::UpdateStatic(bool IsHoldingTape)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "UpdateStatic");

	Params::WBP_K27_C_UpdateStatic Parms{};

	Parms.IsHoldingTape = IsHoldingTape;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_K27.WBP_K27_C.UpdateSegmentCount
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTheOnryoStatusData*              KillerData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_K27_C::UpdateSegmentCount(class UTheOnryoStatusData* KillerData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "UpdateSegmentCount");

	Params::WBP_K27_C_UpdateSegmentCount Parms{};

	Parms.KillerData = KillerData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_K27.WBP_K27_C.SetSurvivor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ActiveStateChanged                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    FullCondemnedChanged                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTheOnryoStatusData*              KillerData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_K27_C::SetSurvivor(bool ActiveStateChanged, bool FullCondemnedChanged, class UTheOnryoStatusData* KillerData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "SetSurvivor");

	Params::WBP_K27_C_SetSurvivor Parms{};

	Parms.ActiveStateChanged = ActiveStateChanged;
	Parms.FullCondemnedChanged = FullCondemnedChanged;
	Parms.KillerData = KillerData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_K27.WBP_K27_C.SetKillerData
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPlayerStatusViewData            Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_K27_C::SetKillerData(const struct FPlayerStatusViewData& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "SetKillerData");

	Params::WBP_K27_C_SetKillerData Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_K27.WBP_K27_C.SetKiller
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ActiveStateChanged                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    FullCondemnedChanged                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTheOnryoStatusData*              KillerData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_K27_C::SetKiller(bool ActiveStateChanged, bool FullCondemnedChanged, class UTheOnryoStatusData* KillerData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "SetKiller");

	Params::WBP_K27_C_SetKiller Parms{};

	Parms.ActiveStateChanged = ActiveStateChanged;
	Parms.FullCondemnedChanged = FullCondemnedChanged;
	Parms.KillerData = KillerData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_K27.WBP_K27_C.SetK27Data
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsLocalKiller                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTheOnryoStatusData*              KillerData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_K27_C::SetK27Data(bool IsLocalKiller, class UTheOnryoStatusData* KillerData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "SetK27Data");

	Params::WBP_K27_C_SetK27Data Parms{};

	Parms.IsLocalKiller = IsLocalKiller;
	Parms.KillerData = KillerData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_K27.WBP_K27_C.SequenceEvent__ENTRYPOINTWBP_K27
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_K27_C::SequenceEvent__ENTRYPOINTWBP_K27()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "SequenceEvent__ENTRYPOINTWBP_K27");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_K27.WBP_K27_C.FullCondemnedLoop
// (BlueprintCallable, BlueprintEvent)

void UWBP_K27_C::FullCondemnedLoop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "FullCondemnedLoop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_K27.WBP_K27_C.ExecuteUbergraph_WBP_K27
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_K27_C::ExecuteUbergraph_WBP_K27(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "ExecuteUbergraph_WBP_K27");

	Params::WBP_K27_C_ExecuteUbergraph_WBP_K27 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_K27.WBP_K27_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_K27_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_K27_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

