#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NotEnoughCurrencyModal

#include "Basic.hpp"

#include "WBP_NotEnoughCurrencyModal_classes.hpp"
#include "WBP_NotEnoughCurrencyModal_parameters.hpp"


namespace SDK
{

// Function WBP_NotEnoughCurrencyModal.WBP_NotEnoughCurrencyModal_C.ExecuteUbergraph_WBP_NotEnoughCurrencyModal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_NotEnoughCurrencyModal_C::ExecuteUbergraph_WBP_NotEnoughCurrencyModal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotEnoughCurrencyModal_C", "ExecuteUbergraph_WBP_NotEnoughCurrencyModal");

	Params::WBP_NotEnoughCurrencyModal_C_ExecuteUbergraph_WBP_NotEnoughCurrencyModal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_NotEnoughCurrencyModal.WBP_NotEnoughCurrencyModal_C.SetTooltipData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FNotEnoughCurrencyModalViewData  Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_NotEnoughCurrencyModal_C::SetTooltipData(const struct FNotEnoughCurrencyModalViewData& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotEnoughCurrencyModal_C", "SetTooltipData");

	Params::WBP_NotEnoughCurrencyModal_C_SetTooltipData Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_NotEnoughCurrencyModal.WBP_NotEnoughCurrencyModal_C.StartCloseAnimation
// (Event, Protected, BlueprintEvent)

void UWBP_NotEnoughCurrencyModal_C::StartCloseAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotEnoughCurrencyModal_C", "StartCloseAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NotEnoughCurrencyModal.WBP_NotEnoughCurrencyModal_C.StartOpenAnimation
// (Event, Protected, BlueprintEvent)

void UWBP_NotEnoughCurrencyModal_C::StartOpenAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotEnoughCurrencyModal_C", "StartOpenAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NotEnoughCurrencyModal.WBP_NotEnoughCurrencyModal_C.StopCloseAnimation
// (Event, Protected, BlueprintEvent)

void UWBP_NotEnoughCurrencyModal_C::StopCloseAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotEnoughCurrencyModal_C", "StopCloseAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NotEnoughCurrencyModal.WBP_NotEnoughCurrencyModal_C.StopOpenAnimation
// (Event, Protected, BlueprintEvent)

void UWBP_NotEnoughCurrencyModal_C::StopOpenAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotEnoughCurrencyModal_C", "StopOpenAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NotEnoughCurrencyModal.WBP_NotEnoughCurrencyModal_C.WidgetAnimationEvt_FadeIn_K2Node_WidgetAnimationEvent_2
// (BlueprintEvent)

void UWBP_NotEnoughCurrencyModal_C::WidgetAnimationEvt_FadeIn_K2Node_WidgetAnimationEvent_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotEnoughCurrencyModal_C", "WidgetAnimationEvt_FadeIn_K2Node_WidgetAnimationEvent_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NotEnoughCurrencyModal.WBP_NotEnoughCurrencyModal_C.WidgetAnimationEvt_FadeOut_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void UWBP_NotEnoughCurrencyModal_C::WidgetAnimationEvt_FadeOut_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NotEnoughCurrencyModal_C", "WidgetAnimationEvt_FadeOut_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}

}

